name:                netchk
version:             0.1.0.0
github:              "githubuser/netchk"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/netchk#readme>

dependencies:
- base >= 4.7 && < 5
- http-client
- http-client-tls
- http-conduit
- aeson
- http-types
- dns
- bytestring
- network
- pretty-terminal
- ansi-terminal
- connection
- tls
- x509-system
- optparse-applicative
- logging
- text
- gnuplot
- split
- safe
- time
- extra
- lens
- network-simple-tls
- asciichart
- attoparsec
- unix
- bits
- pcap
- terminal-size

library:
  source-dirs: src

executables:
  netchk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - netchk

tests:
  netchk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - netchk
